title: Desmos Graphs
description: A collection of interactive mathematical visualizations
baseurl: "/desmos-site"
url: "https://mrurbo.github.io/desmos-site"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
